version: "3.8"

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jpa-dev
    command: ./mnvw spring-boot:run
    restart: always
    ports:
      - "1234:1234"
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - courses-mysql-data:/var/lib/mysql

volumes:
  courses-mysql-data: